### ISSUE TITLE
About the vtkPolyDataBooleanFilter  

### ISSUE THREAD

**Issue by Alexander-Jing** [hyunseoki/Vessel_Surface_Reconstruction-C#1]
vtkBooleanOperationPolyDataFilter can be used as the replacement of vtkPolyDataBooleanFilter  
#include <vtkBooleanOperationPolyDataFilter.h>
you can refer to https://vtk.org/doc/nightly/html/classvtkBooleanOperationPolyDataFilter.html#details

**Comment by hyunseoki** [comment]
When I was working on this project, 'vtkBooleanOperationPolyDataFilter ' was unstable and unexpected flaw occurs
(about 3 years ago)
see https://discourse.vtk.org/t/mesh-flaw-occurs-when-using-vtkbooleanoperation/1502
As far as I know, the algorithm has been modified and works well
